#!/usr/bin/env python3
"""
Integration tests for the short-cadence continuation wiring inside
evolution/advance.py::_resolve_prior_attempt()'s failure branch (added
2026-09-03, proposal 0b81c374) -- proves the REAL shared-routing behavior
against REAL Proposal + LedgerRecord state on disk, not mocks. The
production logic under test was generated by gpt-oss:20b (jobs 62270bb8 for
the wiring, fb5425ba/90f6f69f/189173a7 for the job_ledger.py helpers it
calls); this test file was authored directly as validation/regression
harness for that shared-routing change, per this project's existing
distinction between "the target implementation" (must be model-generated)
and "test/validation infrastructure" (Claude may build).

Attempt ordinal source (Founder decision, 2026-09-03): Proposal.
implementation_job_ids, NOT LedgerRecord.resume_count -- the former is
proposal-level, durable across restart/re-entry, and the one _resolve_
prior_attempt() actually reads (it already receives `p`, no signature
change needed).

Run: python3 tests/test_short_cadence_retry_integration.py
"""
from __future__ import annotations

import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import job_ledger
from evolution import advance
from evolution import proposal as proposal_mod

FAILURES: list[str] = []


def check(name: str, condition: bool, detail: str = "") -> None:
    status = "PASS" if condition else "FAIL"
    print(f"[{status}] {name}" + (f" — {detail}" if detail and not condition else ""))
    if not condition:
        FAILURES.append(name)


def _make_low_risk_proposal(weakness: str) -> proposal_mod.Proposal:
    return proposal_mod.create(observed_weakness=weakness, proposed_upgrade="n/a", risk_score="low", origin="manual")


def _cleanup(proposal_id: str, note: str) -> None:
    p = proposal_mod.load(proposal_id)
    if p.status not in proposal_mod.CLOSED_STATUSES:
        proposal_mod.advance(proposal_id, proposal_mod.ProposalStatus.REJECTED, note=note)
        proposal_mod.record_lesson(proposal_id, note)


def _make_failed_job(*, error_class: str, terminal_result: str, risk_class: str = "low",
                      approval_state: str = "not_required", authority_state: str = "granted") -> str:
    """A real, durable, terminal FAILED job_ledger record -- same shape
    bridge.py/omniengineer_harness.py produce (AUTHORIZED checkpoint first,
    matching every real call site, then the terminal FAILED checkpoint)."""
    job_id = str(uuid.uuid4())
    job_ledger.create(job_id, task=f"synthetic short-cadence test {job_id}", requested_by="test", sandbox_path="/tmp")
    job_ledger.checkpoint(job_id, job_ledger.JobState.AUTHORIZED, risk_class=risk_class,
                           approval_state=approval_state, authority_state=authority_state)
    job_ledger.checkpoint(job_id, job_ledger.JobState.FAILED, terminal_result=terminal_result, error_class=error_class)
    return job_id


def _backdate_updated_at(job_id: str, seconds_ago: int) -> None:
    """Same established pattern as tests/test_bridge_ledger.py's
    _backdate_heartbeat() -- direct load + mutate + the module's own
    _atomic_write_json(), never hand-editing ledger.json as raw text."""
    r = job_ledger.load(job_id)
    r.updated_at = (datetime.now(timezone.utc) - timedelta(seconds=seconds_ago)).isoformat()
    job_ledger._atomic_write_json(job_ledger._path(job_id), job_ledger.asdict(r))


def test_A_transient_not_ready_waits_no_dispatch() -> None:
    p = _make_low_risk_proposal("synthetic A: transient not ready")
    job_id = _make_failed_job(error_class="infra", terminal_result="timeout")
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p = proposal_mod.load(p.proposal_id)
    job, note, refuse = advance._resolve_prior_attempt(p, requested_by="test")
    check("A: refuse=True — waiting, not yet retry-ready (just failed, backoff is 60-120s)", refuse is True, note)
    check("A: no job returned — no dispatch", job is None)
    p_after = proposal_mod.load(p.proposal_id)
    check("A: attempt ordinal (implementation_job_ids) unchanged by the wait itself",
          p_after.implementation_job_ids == [job_id], p_after.implementation_job_ids)
    _cleanup(p.proposal_id, "test A cleanup")


def test_B_transient_ready_allows_exactly_one_continuation() -> None:
    p = _make_low_risk_proposal("synthetic B: transient ready")
    job_id = _make_failed_job(error_class="infra", terminal_result="model_unavailable")
    _backdate_updated_at(job_id, 200)  # well past the 60-120s bound
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p = proposal_mod.load(p.proposal_id)
    job, note, refuse = advance._resolve_prior_attempt(p, requested_by="test")
    check("B: refuse=False — retry-ready, proceeds to the existing attempt-budget/router path", refuse is False, note)
    check("B: job is None — a genuinely fresh attempt, not a reused one", job is None)
    _cleanup(p.proposal_id, "test B cleanup")


def test_C_non_transient_excluded_from_new_path() -> None:
    p = _make_low_risk_proposal("synthetic C: non-transient excluded")
    job_id = _make_failed_job(error_class="validation", terminal_result="succeeded_validation_failed")
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p = proposal_mod.load(p.proposal_id)
    job, note, refuse = advance._resolve_prior_attempt(p, requested_by="test")
    check("C: refuse=False — falls through to the pre-existing (unchanged) behavior", refuse is False, note)
    check("C: job is None", job is None)
    check("C: note names the failure as non-transient, not silently identical to the old generic message",
          "non-transiently" in note, note)
    _cleanup(p.proposal_id, "test C cleanup")


def test_D_gate_stop_is_detected_and_surfaced() -> None:
    """The gate-stop check here is intentionally a short-circuit/
    observability improvement, not a new hard block: the real backstop for
    an authority-gated proposal is authority_policy.classify()'s
    impl.terminal_reject inside _implementation_router() (unchanged,
    already covered by test_evolution_advance.py's own authority tests) --
    a fresh attempt on the same task text deterministically re-rejects
    there. This test proves _resolve_prior_attempt() correctly DETECTS the
    gate condition and reports it distinctly, without corrupting its
    return contract (still (None, note, False), same as the non-transient
    case) -- it does NOT claim to prove system-wide "no attempt consumed",
    which is a property of the unchanged downstream router, not this
    function."""
    p = _make_low_risk_proposal("synthetic D: gate stop detected")
    job_id = _make_failed_job(error_class="infra", terminal_result="timeout",
                               risk_class="founder_gated", approval_state="pending_approval", authority_state="granted")
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p = proposal_mod.load(p.proposal_id)
    job, note, refuse = advance._resolve_prior_attempt(p, requested_by="test")
    check("D: refuse=False — return contract unchanged (same shape as every other branch)", refuse is False, note)
    check("D: note names the gate decision distinctly", "gate decision" in note, note)
    _cleanup(p.proposal_id, "test D cleanup")


def test_E_active_work_branch_unaffected() -> None:
    """Proves this new code left the pre-existing active-work branch
    completely untouched — it lives entirely inside the OLD function's
    final 'failure'/'unknown' branch, never reached for an active job."""
    p = _make_low_risk_proposal("synthetic E: active work unaffected")
    job_id = str(uuid.uuid4())
    job_ledger.create(job_id, task=f"synthetic active {job_id}", requested_by="test", sandbox_path="/tmp")
    job_ledger.checkpoint(job_id, job_ledger.JobState.EDITING)
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p = proposal_mod.load(p.proposal_id)
    job, note, refuse = advance._resolve_prior_attempt(p, requested_by="test")
    check("E: refuse=True — still active, exactly as before this change existed", refuse is True, note)
    _cleanup(p.proposal_id, "test E cleanup")


def test_F_restart_before_ready_no_duplicate() -> None:
    """Simulates two separate cycles (two independent reloads of durable
    state) while still not retry-ready — must agree both times and never
    grow proposal lineage just from being asked twice."""
    p = _make_low_risk_proposal("synthetic F: restart before ready")
    job_id = _make_failed_job(error_class="infra", terminal_result="timeout")
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p1 = proposal_mod.load(p.proposal_id)
    job1, note1, refuse1 = advance._resolve_prior_attempt(p1, requested_by="test")
    p2 = proposal_mod.load(p.proposal_id)  # simulates a fresh process reloading durable state
    job2, note2, refuse2 = advance._resolve_prior_attempt(p2, requested_by="test")
    check("F: both independent reloads refuse identically (not yet ready)",
          refuse1 is True and refuse2 is True, (refuse1, refuse2))
    p_final = proposal_mod.load(p.proposal_id)
    check("F: implementation_job_ids unchanged across both calls",
          p_final.implementation_job_ids == [job_id], p_final.implementation_job_ids)
    _cleanup(p.proposal_id, "test F cleanup")


def test_G_restart_after_ready_allows_one_continuation() -> None:
    p = _make_low_risk_proposal("synthetic G: restart after ready")
    job_id = _make_failed_job(error_class="infra", terminal_result="timeout")
    _backdate_updated_at(job_id, 200)
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    p_reloaded = proposal_mod.load(p.proposal_id)  # simulates a fresh process/restart reading durable state
    job, note, refuse = advance._resolve_prior_attempt(p_reloaded, requested_by="test")
    check("G: refuse=False after a simulated restart, once genuinely ready", refuse is False, note)
    _cleanup(p.proposal_id, "test G cleanup")


def test_H_repeated_calls_never_grow_lineage_on_their_own() -> None:
    """No infinite-retry surface: repeatedly asking (as repeated
    advance_eligible() cycles would) while not-yet-ready must never itself
    create a job or mutate proposal lineage -- _resolve_prior_attempt()
    never calls submit_job(); only advance_one()'s own router does that,
    gated by the unchanged, separate MAX_IMPLEMENTATION_ATTEMPTS ceiling."""
    p = _make_low_risk_proposal("synthetic H: repeated calls bounded")
    job_id = _make_failed_job(error_class="infra", terminal_result="timeout")
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    for i in range(5):
        p_i = proposal_mod.load(p.proposal_id)
        job, note, refuse = advance._resolve_prior_attempt(p_i, requested_by="test")
        check(f"H: repeated call #{i + 1} still refuses cleanly, no exception", refuse is True, note)
    p_final = proposal_mod.load(p.proposal_id)
    check("H: implementation_job_ids never grew across 5 repeated calls",
          p_final.implementation_job_ids == [job_id], p_final.implementation_job_ids)
    _cleanup(p.proposal_id, "test H cleanup")


def test_I_fine_grained_subhourly_checks_track_real_elapsed_time() -> None:
    """No hourly-watchdog dependency: readiness is checked at several
    points seconds apart (all far under an hour) and tracks real elapsed
    time purely from persisted state, exactly as job_ledger.is_retry_ready
    itself already proves in isolation (test_job_ledger_no_watchdog_
    dependency.py) -- this proves the SAME property holds through the
    real _resolve_prior_attempt() call path, not just the bare helper."""
    p = _make_low_risk_proposal("synthetic I: sub-hourly checks")
    job_id = _make_failed_job(error_class="infra", terminal_result="timeout")
    proposal_mod.append_implementation_job(p.proposal_id, job_id)
    # attempt=1 -> backoff is exactly 60s (60 + (1-1)%61); values kept well
    # clear of that boundary to avoid execution-time flakiness.
    for seconds_ago, expect_ready in [(200, True), (70, True), (30, False)]:
        _backdate_updated_at(job_id, seconds_ago)
        p_i = proposal_mod.load(p.proposal_id)
        job, note, refuse = advance._resolve_prior_attempt(p_i, requested_by="test")
        check(f"I: seconds_ago={seconds_ago} -> refuse={not expect_ready} as expected",
              refuse == (not expect_ready), note)
    _cleanup(p.proposal_id, "test I cleanup")


if __name__ == "__main__":
    test_A_transient_not_ready_waits_no_dispatch()
    test_B_transient_ready_allows_exactly_one_continuation()
    test_C_non_transient_excluded_from_new_path()
    test_D_gate_stop_is_detected_and_surfaced()
    test_E_active_work_branch_unaffected()
    test_F_restart_before_ready_no_duplicate()
    test_G_restart_after_ready_allows_one_continuation()
    test_H_repeated_calls_never_grow_lineage_on_their_own()
    test_I_fine_grained_subhourly_checks_track_real_elapsed_time()
    if FAILURES:
        print(f"\n{len(FAILURES)} failing test(s): {FAILURES}")
    else:
        print("\nAll tests passed.")
